### ISSUE TITLE
Haseiq did not start after Update to 2025.8.2

### ISSUE THREAD

**Issue by lighthousehh** [Xsez/haseiq#1]
The following errors occurred: 
Logger: custom_components.haseiq.IQstove
Quelle: custom_components/haseiq/IQstove.py:182
Task failed with exception: 'ClientConnection' object has no attribute 'open'
 
Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/haseiq/IQstove.py", line 99, in listen
    if self.websocket and self.websocket.open:
                          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'open'

Can you please check?
Thanks

**Comment by Xsez** [comment]
I've updated the integration to make it compatible with the newest HA version. Tested it for a few hours. Hot summer at the moment, will definitely not try a burn cycle... ;)

You might need to unplug your oven for 10s to restart the controller. I think the oven denies new connections after too many failed attempts from the broken integration.

**Comment by Xsez** [comment]
I'm going to close this ticket. If anything is wrong, please open up a new one.
